apiVersion: v1
kind: Service
metadata:
  name: qod-db
  labels:
    app: qod-db
    tier: data
spec:
  type: ClusterIP
  ports:
    - name: cockroachdb
      port: 26257
      targetPort: 26257
      protocol: TCP 
  selector:
    app: qod-db
